// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_cognito_identity_pool_id': 'us-west-2:37b00cd5-1fd4-4f24-8f4b-accbffe51d95',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'testkanza-hosting-mobilehub-1152812047',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd37mx4xe1ayqyo.cloudfront.net',
    'aws_project_id': '8eb2984a-88bf-4fa9-8225-5206ca4cbee1',
    'aws_project_name': 'test-kanza',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'testkanza-mobilehub-1152812047',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_YSzB91BvM',
    'aws_user_pools_web_client_id': '5j8b8cag3qfg6dg2u77780kn0v',
}

export default awsmobile;
