// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:34cb1061-4db8-4bfa-90d3-ffb9472b6aa6',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'kazanfe-hosting-mobilehub-2139429094',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1h7g29ai179r1.cloudfront.net',
    'aws_mobile_analytics_app_id': 'bf364251e7584fdb8c587fe649cd1a3b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'ab68ce68-b44a-4585-8914-4aa2d6f1db6a',
    'aws_project_name': 'kazan-fe-2018-04-26-13-20-25',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'kazanfe-mobilehub-2139429094',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_gCZ5ooN1l',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4ofl13emd1bs98s5iqlla7pu7g',
}

export default awsmobile;
